services:
  - type: web
    name: fastapi-cache-proxy
    env: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: BRAPI_TOKEN
        value: "mLN5Xjn8W9B91cjLdmG3B2"
      - key: CACHE_TTL
        value: "1200"